### ISSUE TITLE
wxPython 4 compatibility: wx.Menu does not have SetCheckable method

### ISSUE THREAD

**Issue by josephsl** [NVDARemote/NVDARemote#171]
Hi,

As of March 13, 2018 build of NVDA next snapshots, GUI is powered by wxPython 4. This breaks Remote add-on because:

ERROR - globalPluginHandler.initialize (09:19:12.835):
Error initializing global plugin <class 'globalPlugins.remoteClient.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 32, in initialize
  File "C:\Users\User\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 56, in __init__
  File "C:\Users\User\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 104, in create_menu
AttributeError: 'MenuItem' object has no attribute 'SetCheckable'

This is Remote add-on 2.1 on Windows 10. I propose resolving this as soon as possible so NVDA next branch users can test compatibility between this add-on and NVDA Core. Thanks.

**Comment by josephsl** [comment]
CC @LeonardDer
