### ISSUE TITLE
error on exiting nvda with remote 1.1

### ISSUE THREAD

**Issue by fisher729** [NVDARemote/NVDARemote#36]
When closing NVDA, the following error is displayed with Remote version 1.1:
Error terminating global plugin <globalPlugins.remoteClient.GlobalPlugin object at 0x04910070>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 40, in terminate
  File "C:\Users\Andre Fisher\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 128, in terminate
  File "wx\_core.pyc", line 16711, in __getattr__
PyDeadObjectError: The C++ part of the Menu object has been deleted, attribute access no longer allowed.
Using Master snapshot of NVDA (11221,5502b74)

**Comment by esmobg** [comment]
please assign with developer for fast repair bugs
  best  regards esmo

**Comment by pzajda** [comment]
[Pull request #35](https://github.com/NVDARemote/NVDARemote/pull/35) can solve this issue.

**Comment by ctoth** [comment]
This has been fixed in #35

**Comment by esmobg** [comment]
nice thanks
